:hivemq-link: http://www.hivemq.com
:hivemq-extension-docs-link: http://www.hivemq.com/docs/extensions/latest/
:hivemq-extension-docs-archetype-link: http://www.hivemq.com/docs/extensions/latest/#maven-archetype-chapter
:hivemq-blog-tools: http://www.hivemq.com/mqtt-toolbox
:maven-documentation-profile-link: http://maven.apache.org/guides/introduction/introduction-to-profiles.html
:hivemq-support: http://www.hivemq.com/support/
:hivemq-testcontainer: https://github.com/hivemq/hivemq-testcontainer
:hivemq-mqtt-client: https://github.com/hivemq/hivemq-mqtt-client
:catfish-repo: https://www.github.com/micli/Catfish
:taosdata-doc: https://www.taosdata.com/en/documentation/

== HiveMQ TDengine Extension (Codename: Catfish)

*Type*: Data Persistent Extension

*Version*: 1.0

*License*: MIT

=== Purpose

This TDengine extension is used for save mqtt data to TDengine database.

Base on read the {hivemq-extension-docs-link}[HiveMQ Extension Documentation] to grasp the core concepts of HiveMQ extension development. It implements PublishInboundInterceptor interface and retrieves mqtt message from onInboundPublish function.

The TDengineHttpClient implements REST API communication to TDengine service. 


=== Installation

. Clone this repository into a Java 11 maven project.
. Run `mvn package` goal from Maven to build the extension.
. Move the file: "target/hivemq-tdengine-extension-0.1-distribution.zip" to the directory: "HIVEMQ_HOME/extensions"
. Unzip the file.
. Configure correct TDengine connect information in TDengine.properties.
. Start HiveMQ by HIVEMQ_HOME/bin/run.sh.

=== Manual Testing

Connect with an {hivemq-blog-tools}[MQTT client] of your choice. You should see a log message with its identifier and MQTT version.


=== Need help?

Please visit {catfish-repo}[*code repository*] on GitHub.

TDengine documentation is {taosdata-doc}[*HERE*].

If you encounter any problems, we are happy to help. The best place to get in contact is our {hivemq-support}[support].

